# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: mysql:5.7
        env:
          MYSQL_USER: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up database schema
        run: |
          RAILS_ENV=test bundle exec rake parallel:drop
          RAILS_ENV=test bundle exec rake parallel:create
          RAILS_ENV=test bundle exec rake parallel:migrate        

      - name: Run tests
        run: RAILS_ENV=test bundle exec rake parallel:spec
        env:
          TZ: Asia/Tokyo
          MYSQL_USER: root
